# Generated by Django 5.0.6 on 2024-07-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0002_movie_delete_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
