# Generated by Django 5.0.6 on 2024-07-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('netflixapp', '0006_delete_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=100)),
                ('genre', models.IntegerField(choices=[(1, 'Imaginative Adventures'), (2, 'New to Stremia'), (3, 'Action Movies'), (4, 'Us action & Adventure Movies'), (5, 'Us movie dubbed in Tamil'), (6, 'Blockbuster Us Comidies')])),
                ('description', models.TextField(max_length=500)),
                ('cover_image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
