# Generated by Django 5.0.6 on 2024-07-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0008_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
    ]
