# Generated by Django 5.0.6 on 2024-07-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0010_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=100)),
                ('genre', models.IntegerField(choices=[(1, 'Tv show dubbed in Tamil'), (2, 'Violent movies'), (3, 'Only on Streamia'), (4, 'Sci-Fi Films'), (5, 'Crime action'), (6, 'Epics')])),
                ('description', models.TextField(max_length=500)),
                ('cover_image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
