# Generated by Django 5.0.6 on 2024-07-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='video',
            field=models.FileField(default=1, upload_to='media/videos/'),
            preserve_default=False,
        ),
    ]
