# Generated by Django 5.0.6 on 2024-07-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0012_movies_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='video',
            field=models.FileField(default=1, upload_to='media/videos/'),
            preserve_default=False,
        ),
    ]
